### ISSUE TITLE
Credentials

### ISSUE THREAD

**Issue by Jane03** [toshiakit/AnalyzeTwitter#1]
Hello, 
 I'm trying your codes in order to get the tweets but i have errors that my credentials are not valid.
 I have tried to figure out the problem but no way.
 Can you hepl me please?

Thanks you

**Comment by toshiakit** [comment]
Hi, more recent version of this post is available. http://blogs.mathworks.com/loren/2017/02/07/analyzing-fake-news-with-twitter/

Here is the video that walks through my code. 
http://blogs.mathworks.com/videos/2017/03/09/setting-up-and-running-toshis-blog-post-code-to-analyze-tweets-about-fake-news/
